### PR TITLE
fix(api): fix accidental exhaustive matching on `metadata::Kind`

### LINKED ISSUE #270: Broken compile with tracing-core 0.1.22
A recent change to `tracing-core` in tokio-rs/tracing#1891 which is used by recently released `tracing` 0.1.29 causes broken compiles due to Kind being changed to a u8 rather than an enum. Manually pinning `tracing-core` to 0.1.21 fixes the issue.

```
error[E0004]: non-exhaustive patterns: `Kind(0_u8)` and `Kind(3_u8..=u8::MAX)` not covered
  --> /home/arlyon/.cargo/registry/src/github.com-1ecc6299db9ec823/console-api-0.1.1/src/common.rs:20:15
   |
20 |         match kind {
   |               ^^^^ patterns `Kind(0_u8)` and `Kind(3_u8..=u8::MAX)` not covered
   |
   = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms
   = note: the matched value is of type `tracing_core::Kind`
```

Happy to open a PR; how should we handle cases where the `tracing_core::metadata::Kind` is not covered? Maybe we should also use a u8 to match?

### PR DESCRIPTION
**Pull request by hawkw**
The `tracing_core::metadata::Kind` type was not intended to be matched
exhaustively, so that its internal representation could be changed
without causing a breaking change. However, some fairly recent compiler
changes broke this, and made the type exhaustively matched. This
resulted in `tracing-core` 0.1.22 breaking `console-api`.

This PR fixes the breakage by changing `console-api` to avoid
exhaustively matching on `Kind`s.

Fixes #270

### CODE REVIEW

**Comment by hawkw** [comment]
Once this is published, I think we may need to yank all previous versions of `console-api`, so that `cargo-install` always uses the latest version? Or, we can bump `tokio-console`'s dependency and publish a new version of it as well.

**Comment by guswynn** [comment]
This looks good to me, but is there any reason not to just delete the whole `From` impl? it appears to be unused? Is it just because it now technically a public api?

edit: answered in the other issue

**Comment by hawkw** [comment]
> This looks good to me, but is there any reason not to just delete the whole `From` impl? it appears to be unused? Is it just because it now technically a public api?
> 
> edit: answered in the other issue

yeah, deleting the `From` impl would require releasing `console-api` 0.2, which i don't super want to do...

**Review by seanmonstar — APPROVED** [review]
